### ISSUE TITLE
PR提交有多个提交文本时，没有转成一行字符串导致通知参数错误

### ISSUE THREAD

**Issue by jefferyjob** [jefferyjob/notify-actions#14]
https://github.com/jefferywork/example-deploy-php/actions/runs/11314421109/job/31464388000

<img width="1054" alt="image" src="https://github.com/user-attachments/assets/8acd5a9e-4eec-4c22-b48e-56bbeaf1b61c">
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/1a62095d-4905-42e0-8648-a84da180bc7f">

**Comment by jefferyjob** [comment]
包含双引号的错误 https://github.com/jefferywork/example-deploy-php/actions/runs/11314625807/job/31464827484

<img width="936" alt="image" src="https://github.com/user-attachments/assets/12c12c72-3916-4f7d-9744-72860c8346db">

**Comment by jefferyjob** [comment]
错误出现在使用 GitHub Actions 的 `${{ github.event.head_commit.message }}` 表达式时，由于直接将其包含在双引号中，而 GitHub Actions 的表达式在某些环境（如 shell）中不能直接使用双引号进行嵌套或命令替换。

### 问题分析

`COMMIT_MESSAGE="${{ github.event.head_commit.message }}"` 这种形式用于 GitHub Actions YAML 文件中的上下文表达式，但在 `bash` shell 中，这些表达式需要在 `run` 部分外被解析。GitHub Actions 在运行时会解析 `${{ }}`，并将实际的值传入 Shell 中。

因此，需要确保表达式在被 GitHub Actions 解析后正确传递给 Shell，而不是在 `bash` 中引发语法错误。

### 修复方案

为了避免这种语法错误，可以通过以下方式修正代码：

#### 避免在 `run` 脚本中直接使用 GitHub 上下文

在 `run` 部分外处理 GitHub Actions 上下文变量，然后将该变量传递给 Shell 脚本。

```yaml
runs:
  using: 'composite'
  steps:
    - name: Auto get env
      shell: bash
      run: |
        COMMIT_MESSAGE="$COMMIT_MESSAGE"
        # 省略... ... 
```

### 详细说明：

1. **`env`**：将 `github.event.head_commit.message` 提取到 `env` 变量中，将其传递到 Shell 环境变量 `COMMIT_MESSAGE`。这样可以避免在 `run` 部分中直接使用 `${{ }}`。
   
2. **`run`**：在 `run` 代码块中，可以直接使用 `$COMMIT_MESSAGE`，因为它已经通过 `env` 传递进来了。
